project_id = "neoavpqgetjwachsubiz"

[functions.admin-create-user]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = false

[functions.send-admin-route-email]
verify_jwt = false

[functions.signup_user]
verify_jwt = false

[functions.verify_signup_otp]
verify_jwt = false

[functions.send_password_reset_otp]
verify_jwt = false

[functions.reset_password]
verify_jwt = false

[functions.get-vapid-public-key]
verify_jwt = false

[functions.send-status-change-email]
verify_jwt = false

[functions.get-google-maps-key]
verify_jwt = false
